site_name: Yihengçš„ç¬”è®°æœ¬
site_url: http://codeheng.github.io
repo_name: Yiheng's NoteBook
repo_url: https://github.com/codeheng/codeheng.github.io

nav:
  - ğŸ¡ ä¸»é¡µ: 
    - index.md
    - â¤ï¸ å…³äºæˆ‘: home/about.md  

  - ğŸ“–æ ¸å¿ƒåŸºç¡€çŸ¥è¯†:
    - æ ¸å¿ƒåŸºç¡€çŸ¥è¯†/index.md
    - ç®—æ³•:
      - LeetCodeåˆ·é¢˜:
        - Day1 | æ•°ç»„Part1: æ ¸å¿ƒåŸºç¡€çŸ¥è¯†/algorithm/day1.md
        - Day2 | æ•°ç»„Part2: æ ¸å¿ƒåŸºç¡€çŸ¥è¯†/algorithm/day2.md
        - Day3 | é“¾è¡¨Part1: æ ¸å¿ƒåŸºç¡€çŸ¥è¯†/algorithm/day3.md
        - Day4 | é“¾è¡¨Part2: æ ¸å¿ƒåŸºç¡€çŸ¥è¯†/algorithm/day4.md
        - Day5 | å“ˆå¸Œè¡¨Part1: æ ¸å¿ƒåŸºç¡€çŸ¥è¯†/algorithm/day5.md
        - Day6 | å“ˆå¸Œè¡¨Part2: æ ¸å¿ƒåŸºç¡€çŸ¥è¯†/algorithm/day6.md
        - Day7 | å­—ç¬¦ä¸²Part1: æ ¸å¿ƒåŸºç¡€çŸ¥è¯†/algorithm/day7.md
        - Day8 | æ ˆä¸é˜Ÿåˆ—Part1: æ ¸å¿ƒåŸºç¡€çŸ¥è¯†/algorithm/day8.md
    - Linux: 
      - åŸºç¡€: æ ¸å¿ƒåŸºç¡€çŸ¥è¯†/linux/1-basic.md

  - ğŸ”å®‰å…¨:
    - å®‰å…¨/index.md
    - ä»‹ç»: å®‰å…¨/intro.md
    - å¯†ç å­¦:
      - æ¦‚è¿°: å®‰å…¨/å¯†ç å­¦/1-intro.md
      - å¯¹ç§°åŠ å¯†: 
        - å¯¹ç§°åŠ å¯†ä»‹ç»: å®‰å…¨/å¯†ç å­¦/2-symmetric-key.md
        - ä¸€æ¬¡æ€§å¯†ç æœ¬: å®‰å…¨/å¯†ç å­¦/3-one_time_pad.md
        - åˆ†ç»„å¯†ç : å®‰å…¨/å¯†ç å­¦/4-Block-Ciphers.md
        - åˆ†ç»„å¯†ç çš„æ“ä½œæ¨¡å¼: å®‰å…¨/å¯†ç å­¦/5-BC_Opera.md
        - MACs: å®‰å…¨/å¯†ç å­¦/7-MACs.md
        - æµå¯†ç : å®‰å…¨/å¯†ç å­¦/9-stream.md
      - å¯†ç æ•£åˆ—: å®‰å…¨/å¯†ç å­¦/6-hash.md
      - ä¼ªéšæœºæ•°ç”Ÿæˆå™¨: å®‰å…¨/å¯†ç å­¦/8-PRNGs.md
      - Diffie-Hellman: å®‰å…¨/å¯†ç å­¦/10-Diffie_Hellman.md
    - åŒºå—é“¾: 
      - æ¦‚è¿°: å®‰å…¨/åŒºå—é“¾/1-blockchain.md
      - åŒºå—é“¾ç®€ä»‹: å®‰å…¨/åŒºå—é“¾/2-intro.md
      - åŒºå—é“¾:åŠ å¯†å’ŒæŒ–çŸ¿: å®‰å…¨/åŒºå—é“¾/3-chapter.md
      - å»ä¸­å¿ƒåŒ–å…±è¯†æœºåˆ¶: å®‰å…¨/åŒºå—é“¾/4-chapter.md
      

  - ğŸ”æ‚é¡¹:
    - æ‚é¡¹/index.md
    - MarkDownæ•™ç¨‹: æ‚é¡¹/markdown.md
    - Vimæ•™ç¨‹: æ‚é¡¹/Vim.md
    - VScodeæ•™ç¨‹: æ‚é¡¹/vscode.md

  - ğŸ“šè¯»ä¹¦ç¬”è®°: 
    - è¯»ä¹¦ç¬”è®°/index.md
    - æˆ‘ä»¬ä¸ºä»€ä¹ˆè¦ç¡è§‰: è¯»ä¹¦ç¬”è®°/why_we_sleep.md

  - ğŸ’¡ç”Ÿæ´»:
    - ç”Ÿæ´»/index.md
    - 2023å¹´åº¦æ€»ç»“: ç”Ÿæ´»/2024/2023final.md
    - 2024:
      - 1æœˆ: ç”Ÿæ´»/2024/january.md
  
  - ğŸ’ªWorkout:
    - workout/index.md
    - Zone 2: workout/zone2.md
    - å‡è‚¥: workout/fat.md

theme: 
  name: material
  favicon: assets/logo.ico

  icon: 
    logo: material/school-outline
  
  features:
    - search.highlight
    - navigation.tabs # ä¸€çº§å¯¼èˆªåœ¨æ¨ªç€çš„å¯¼èˆªæ 
    - navigation.instant # å³æ—¶åŠ è½½ ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#:~:text=%C2%B6-,Instant%20loading,%C2%B6,-5.0.0
    - content.code.annotate # å¯ä»¥åœ¨ä»£ç å—ä¸­å¢æ·»ç‚¹å‡»å±•ç¤ºçš„æ³¨é‡Šï¼Œå‚è§ https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    #- navigation.tracking # åœ°å€æ ä¸­çš„ URL ä¼šéšå½“å‰ä½ç½®å˜åŒ–ä¸ºå¯¹åº”å°èŠ‚çš„ URL
    - navigation.indexes # å°† index é¡µé¢ç›´æ¥é™„åˆ°å°èŠ‚åä¸Š
    - navigation.top # å›åˆ°é¡¶éƒ¨æŒ‰é’®
    # - navigation.sections # äºŒçº§å¯¼èˆªæ˜¯ç²—ä½“
    # - navigation.expand # å¯¼èˆªé»˜è®¤å±•å¼€
    - toc.follow # toc è·Ÿéš
    # - toc.integrate # æ–‡æ¡£ toc é›†æˆåˆ°æ€»ç›®å½•ä¸­
    - content.code.copy
  
  font: 
    text: Noto Serif SC
    code: Roboto Mono
  
  language: 'zh'

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        
  custom_dir: overrides # ç”¨æ¥æè¯„è®ºçš„ï¼Œå‚è€ƒ https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

extra:
  analytics:
    provider: google
    #property: G-JT9BRCXKJJ
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codeheng
    - icon: fontawesome/solid/envelope
      link: mailto:yihenghhh@gmail.com


edit_uri: ""
copyright: 'æœ¬é¡µé¢çš„å…¨éƒ¨å†…å®¹åœ¨ <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> å’Œ <a href="https://github.com/zTrix/sata-license">SATA</a> åè®®ä¹‹æ¡æ¬¾ä¸‹æä¾›ï¼Œé™„åŠ æ¡æ¬¾äº¦å¯èƒ½åº”ç”¨'

extra_css:
  - stylesheets/extra.css
  - stylesheets/status.css

extra_javascript:
  - javascripts/mathjax.js # æ”¯æŒæ•°å­¦å…¬å¼ï¼Œref : https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/twemoji@latest/dist/twemoji.min.js

# Plugin
plugins:
  - search:
      separator: '[\s\u200b\-]'  # ä¸­æ–‡æœç´¢, pip install jieba
      # å‚è€ƒ:https://squidfunk.github.io/mkdocs-material/blog/2022/05/05/chinese-search-support/?h=%E4%B8%AD%E6%96%87
  - statistics
  #- git-revision-date #æ¯é¡µåº•éƒ¨æ˜¾ç¤ºæ–‡æ¡£æœ€åæ›´æ–°æ—¥æœŸï¼Œå®‰è£… pip install mkdocs-git-revision-date-plugin
  - git-revision-date-localized:  #æ¯ä¸ªé¡µé¢åº•éƒ¨æ·»åŠ æœ¬åœ°åŒ–æ›´æ–°å’Œåˆ›å»ºæ—¥æœŸï¼Œå®‰è£…pip install mkdocs-git-revision-date-localized-plugin
      type: date #æ—¥æœŸæ ¼å¼ï¼Œæœ‰æ•ˆå€¼ä¸ºdateã€datetimeã€iso_dateã€iso_datetime,timeago
      # fallback_to_build_date: true  #é»˜è®¤falseï¼Œå¯ç”¨åˆ™å›é€€åˆ°mkdocs buildæ‰§è¡Œçš„æ—¶é—´
      enable_creation_date: true  #æœ€åæ›´æ–°æ—¥æœŸæ—è¾¹æ˜¾ç¤ºä¸é¡µé¢å…³è”çš„æ–‡ä»¶çš„åˆ›å»ºæ—¥æœŸ

markdown_extensions:
# Python Markdown
  - toc: #ç›®å½•
      permalink: true # link for each title
      title: Table of Content 
  - admonition #è­¦å‘Šæˆ–æ ‡æ³¨
  - pymdownx.details #ç»†èŠ‚æŠ˜å 
  - pymdownx.superfences #è¶…çº§å›´æ 
  - pymdownx.critic 

  - abbr #ç¼©å†™æˆ–åè¯
  - attr_list #å±æ€§åˆ—è¡¨ï¼ˆæŒ‰é’®-é¢œè‰²å›¾æ ‡ï¼‰
  - def_list #å®šä¹‰åˆ—è¡¨
  - footnotes #è¡Œå†…è„šæ³¨
  - tables #è¡¨æ ¼
  - meta #å…ƒæ•°æ®
  - md_in_html #HTML ä¸­çš„ Markdown
  - pymdownx.arithmatex: #æ•°å­¦å…¬å¼
      generic: true
  - pymdownx.betterem: #ç²—ä½“æ–œä½“
      smart_enable: all
  - pymdownx.caret #æ’å…¥è§’æ ‡ç¬¦å·(`^`)
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight #ä»£ç é«˜äº®ï¼Œå¯¹ä»£ç å—ï¼ˆSuperFencesï¼‰å’Œè¡Œå†…ä»£ç å—ï¼ˆInlineHiliteï¼‰çš„è¯­æ³•çªå‡ºæ˜¾ç¤º

  - pymdownx.inlinehilite #è¡Œå†…é«˜äº®
  - pymdownx.keys #é”®ç›˜é”®å’Œç»„åˆ  
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark #åŒç­‰å·(`==`)
  - pymdownx.smartsymbols #æ™ºèƒ½ç¬¦å·
  - pymdownx.tilde # åˆ é™¤çº¿
  - pymdownx.snippets: # å…è®¸å°†å…¶ä»–æ–‡ä»¶å†…å®¹æ’å…¥æ–‡ä»¶ï¼Œè¯­æ³•æ˜¯ --8<-- "filename.ext" ç­‰ï¼Œå‚è§ https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]
  - pymdownx.superfences: # æ­¤é…ç½®å¯ç”¨å¯¹Mermaid.jså›¾è¡¨çš„æœ¬æœºæ”¯æŒ
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: #å†…å®¹é€‰é¡¹å¡
      alternate_style: true 
  - pymdownx.tasklist: #ä»»åŠ¡åˆ—è¡¨
      custom_checkbox: true
  - admonition
  - pymdownx.details
