site_name: Yihengçš„ç¬”è®°æœ¬
site_url: http://codeheng.github.io
repo_name: Yiheng's NoteBook
repo_url: https://github.com/codeheng/codeheng.github.io

nav:
  - ğŸ¡ ä¸»é¡µ: 
    - index.md
    - â¤ï¸ å…³äºæˆ‘: home/about.md  

  - ğŸ“–çŸ¥è¯†:
    - core_knowledge/index.md
    - ç®—æ³•:
      - LeetCodeåˆ·é¢˜:
        - æ•°ç»„: 
          - Day1 | Part1: core_knowledge/algorithm/check_in_everyday/day1.md
          - Day2 | Part2: core_knowledge/algorithm/check_in_everyday/day2.md
        - é“¾è¡¨:
          - Day3 | Part1: core_knowledge/algorithm/check_in_everyday/day3.md
          - Day4 | Part2: core_knowledge/algorithm/check_in_everyday/day4.md
        - å“ˆå¸Œè¡¨:
          - Day5 | Part1: core_knowledge/algorithm/check_in_everyday/day5.md
          - Day6 | Part2: core_knowledge/algorithm/check_in_everyday/day6.md
        - å­—ç¬¦ä¸²: 
          - Day7 | Part1: core_knowledge/algorithm/check_in_everyday/day7.md
        - æ ˆå’Œé˜Ÿåˆ—: 
          - Day8 | Part1: core_knowledge/algorithm/check_in_everyday/day8.md
          - Day9 | Part2: core_knowledge/algorithm/check_in_everyday/day9.md
          - Day10 | Part3: core_knowledge/algorithm/check_in_everyday/day10.md
        - äºŒå‰æ ‘: 
          - Day11 | Part1: core_knowledge/algorithm/check_in_everyday/day11.md
          - Day12 | Part2: core_knowledge/algorithm/check_in_everyday/day12.md
          - Day13 | Part3: core_knowledge/algorithm/check_in_everyday/day13.md
          - Day14 | Part4: core_knowledge/algorithm/check_in_everyday/day14.md
          - Day15 | Part5: core_knowledge/algorithm/check_in_everyday/day15.md
          - Day16 | Part6: core_knowledge/algorithm/check_in_everyday/day16.md
          - Day17 | Part7: core_knowledge/algorithm/check_in_everyday/day17.md
          - Day18 | Part8: core_knowledge/algorithm/check_in_everyday/day18.md
          - Day19 | Part9: core_knowledge/algorithm/check_in_everyday/day19.md
        - å›æº¯ç®—æ³•:
          - Day20 | Part1: core_knowledge/algorithm/check_in_everyday/day20.md
          - Day21 | Part2: core_knowledge/algorithm/check_in_everyday/day21.md
          - Day22 | Part3: core_knowledge/algorithm/check_in_everyday/day22.md
          - Day23 | Part4: core_knowledge/algorithm/check_in_everyday/day23.md
          - Day24 | Part5: core_knowledge/algorithm/check_in_everyday/day24.md
          - Day25 | Part6: core_knowledge/algorithm/check_in_everyday/day25.md
        - è´ªå¿ƒç®—æ³•: 
          - Day26 | Part1: core_knowledge/algorithm/check_in_everyday/day26.md
          - Day27 | Part2: core_knowledge/algorithm/check_in_everyday/day27.md
          - Day28 | Part3: core_knowledge/algorithm/check_in_everyday/day28.md
          - Day29 | Part4: core_knowledge/algorithm/check_in_everyday/day29.md
          - Day30 | Part5: core_knowledge/algorithm/check_in_everyday/day30.md
          - Day31 | Part6: core_knowledge/algorithm/check_in_everyday/day31.md
        - åŠ¨æ€è§„åˆ’:
          - Day32 | Part1: core_knowledge/algorithm/check_in_everyday/day32.md
          - Day33 | Part2: core_knowledge/algorithm/check_in_everyday/day33.md
          - Day34 | Part3: core_knowledge/algorithm/check_in_everyday/day34.md
          - Day35 | Part4: core_knowledge/algorithm/check_in_everyday/day35.md
          - Day36 | Part5: core_knowledge/algorithm/check_in_everyday/day36.md
    - Linux: 
      - åŸºç¡€: core_knowledge/linux/1-basic.md
    - C++:
      - core_knowledge/language/c++/index.md
      - CS106L:
        - åŸºç¡€: core_knowledge/language/c++/cs106l/1-intro.md
    - Lab:
      - CSAPP:
        - core_knowledge/lab/csapp/index.md
        - DataLab: core_knowledge/lab/csapp/01datalab.md

  - ğŸ”å®‰å…¨:
    - security_etc/index.md
    - CS161:
      - ä»‹ç»: security_etc/intro.md
      - å¯†ç å­¦:
        - æ¦‚è¿°: security_etc/cryptography/1-intro.md
        - å¯¹ç§°åŠ å¯†: 
          - å¯¹ç§°åŠ å¯†ä»‹ç»: security_etc/cryptography/2-symmetric-key.md
          - ä¸€æ¬¡æ€§å¯†ç æœ¬: security_etc/cryptography/3-one_time_pad.md
          - åˆ†ç»„å¯†ç : security_etc/cryptography/4-Block-Ciphers.md
          - åˆ†ç»„å¯†ç çš„æ“ä½œæ¨¡å¼: security_etc/cryptography/5-BC_Opera.md
          - MACs: security_etc/cryptography/7-MACs.md
          - æµå¯†ç : security_etc/cryptography/9-stream.md
        - å¯†ç æ•£åˆ—: security_etc/cryptography/6-hash.md
        - ä¼ªéšæœºæ•°ç”Ÿæˆå™¨: security_etc/cryptography/8-PRNGs.md
        - Diffie-Hellman: security_etc/cryptography/10-Diffie_Hellman.md
        - å…¬é’¥å¯†ç : security_etc/cryptography/11-Public-key_Cryptography.md
        - æ•°å­—ç­¾å: security_etc/cryptography/12-digital_signatures.md
        - è¯ä¹¦: security_etc/cryptography/13-certificates.md
        - å¯†ç å“ˆå¸Œ: security_etc/cryptography/14-pwd_hashing.md
        - æ¯”ç‰¹å¸: security_etc/cryptography/bitcoin.md

    - åŒºå—é“¾: 
      - æ¦‚è¿°: security_etc/blockchain/1-blockchain.md
      - åŒºå—é“¾ç®€ä»‹: security_etc/blockchain/2-intro.md
      - åŒºå—é“¾:åŠ å¯†å’ŒæŒ–çŸ¿: security_etc/blockchain/3-chapter.md
      - å»ä¸­å¿ƒåŒ–å…±è¯†æœºåˆ¶: security_etc/blockchain/4-chapter.md
      - æ™ºèƒ½åˆçº¦: security_etc/blockchain/5-smart_contract.md

    - ã€ŠåŒºå—é“¾æŠ€æœ¯ä¸åº”ç”¨ã€‹:
      - 01ç®€ä»‹: security_etc/course/blockchain/01_intro.md
      - æ¯”ç‰¹å¸BTC: 
        - 02å¯†ç å­¦åŸç†: security_etc/course/blockchain/bitcoin/02_cryto.md
        - 03æ•°æ®ç»“æ„: security_etc/course/blockchain/bitcoin/03_data_structure.md
        - 04åè®®: security_etc/course/blockchain/bitcoin/04_protocol.md
        - 05å®ç°: security_etc/course/blockchain/bitcoin/05_BTCå®ç°.md
        - 06ç½‘ç»œ: security_etc/course/blockchain/bitcoin/06_BTC_internet.md
        - 07æŒ–çŸ¿éš¾åº¦: security_etc/course/blockchain/bitcoin/07_BTC_æŒ–çŸ¿éš¾åº¦.md
        - 08åˆ†å‰: security_etc/course/blockchain/bitcoin/08_BTC_fork.md
        - 09åŒ¿åæ€§: security_etc/course/blockchain/bitcoin/09_BTC_anonymity.md

    - ç”µåŠ¨æ±½è½¦ä¸èƒ½æºäº’è”ç½‘:
      - æ¦‚è¿°: security_etc/EvAndEI/intro.md
      - éœ€æ±‚å“åº”: security_etc/EvAndEI/dr.md
      - è™šæ‹Ÿç”µå‚: security_etc/EvAndEI/vpp.md

    - ç§‘ç ”:
      - security_etc/paper/index.md
      - å¸ˆé—¨è®ºæ–‡: security_etc/paper/master_homegate_paper.md
      - è®ºæ–‡è®°å½•: security_etc/paper/paper_records.md
      - ç†è®ºçŸ¥è¯†:
        - ECDLP: security_etc/paper/knowledge/ecdlp.md
        - V2G: security_etc/paper/knowledge/v2g.md
        - æ— è¯ä¹¦å…¬é’¥å¯†ç : security_etc/paper/knowledge/cl_pkc.md
        - åŒçº¿æ€§æ˜ å°„: security_etc/paper/knowledge/bilinear_pairing.md
        - é‡å­åŠ å¯†: security_etc/paper/knowledge/quantum_crypto.md
        - å¯è¯æ˜å®‰å…¨: security_etc/paper/knowledge/provably_secure.md
      - å®éªŒ:
        - åº“: security_etc/paper/tool/lib.md
        - å¯†ç å­¦ç¬¦å·: security_etc/paper/tool/symbol.md
  - ğŸ”æ‚é¡¹:
    - mess/index.md
    - å·¥å…·æ”¶é›†: mess/tool.md
    - MarkDown: mess/markdown.md
    - Vim: mess/Vim.md
    - VScode: mess/vscode.md
    - Docker: mess/docker.md
    - LaTex: mess/latex.md

  - ğŸ”‘Eng:
    - eng/index.md
    - å•è¯: eng/word.md
    - ä½œæ–‡ç§¯ç´¯: eng/writing.md


  - ğŸ“šä¹¦ç±: 
    - writing_note/index.md
    - Book: writing_note/book_records.md
    - æˆ‘ä»¬ä¸ºä»€ä¹ˆè¦ç¡è§‰: writing_note/why_we_sleep.md
    - æ§ç³–é©å‘½: writing_note/Glucose_Revolution.md

  - ğŸ’¡ç”Ÿæ´»:
    - life/index.md
    - 2023å¹´åº¦æ€»ç»“: life/2024/2023final.md
    - 2024:
      - 1æœˆ: life/2024/24_january.md
      - 2æœˆ: life/2024/24_february.md
      - 3æœˆ: life/2024/24_march.md
      - 4æœˆ: life/2024/24_april.md
      - 5æœˆ: life/2024/24_may.md
      - 6æœˆ: life/2024/24_june.md
      - ä¸‹åŠå¹´: life/2024/24_last_half_years.md
  
  - ğŸ’ªWorkout:
    - workout/index.md
    - Zone 2: workout/zone2.md
    - å‡è‚¥: workout/fat.md
    - è¡€å‹: workout/blood_pressure.md
    - é¥®é£Ÿ:
      - è›‹ç™½è´¨: workout/food/protein.md
    - å¥èº«è®°å½•: workout/records.md
    - å¥èº«åŠ¨ä½œ: workout/fitness_moves.md

  - ğŸ“‚Attachment: 
    - attachment/index.md
    - Slide: attachment/ppt/slide.md

theme: 
  name: material
  favicon: assets/logo.ico

  icon: 
    logo: material/school-outline
  
  features:
    - search.highlight
    - navigation.tabs # ä¸€çº§å¯¼èˆªåœ¨æ¨ªç€çš„å¯¼èˆªæ 
    - navigation.instant # å³æ—¶åŠ è½½ ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#:~:text=%C2%B6-,Instant%20loading,%C2%B6,-5.0.0
    - content.code.annotate # å¯ä»¥åœ¨ä»£ç å—ä¸­å¢æ·»ç‚¹å‡»å±•ç¤ºçš„æ³¨é‡Šï¼Œå‚è§ https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    #- navigation.tracking # åœ°å€æ ä¸­çš„ URL ä¼šéšå½“å‰ä½ç½®å˜åŒ–ä¸ºå¯¹åº”å°èŠ‚çš„ URL
    - navigation.indexes # å°† index é¡µé¢ç›´æ¥é™„åˆ°å°èŠ‚åä¸Š
    - navigation.top # å›åˆ°é¡¶éƒ¨æŒ‰é’®
    # - navigation.sections # äºŒçº§å¯¼èˆªæ˜¯ç²—ä½“
    # - navigation.expand # å¯¼èˆªé»˜è®¤å±•å¼€
    - toc.follow # toc è·Ÿéš
    # - toc.integrate # æ–‡æ¡£ toc é›†æˆåˆ°æ€»ç›®å½•ä¸­
    - content.code.copy
    - content.footnote.tooltips
  
  font: 
    text: Noto Serif SC
    code: Roboto Mono
  
  language: 'zh'

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        
  custom_dir: overrides # ç”¨æ¥æè¯„è®ºçš„ï¼Œå‚è€ƒ https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

extra:
  analytics:
    provider: google
    #property: G-JT9BRCXKJJ
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codeheng
    - icon: fontawesome/solid/envelope
      link: mailto:yihenghhh@gmail.com


edit_uri: ""
copyright: 'æœ¬é¡µé¢çš„å…¨éƒ¨å†…å®¹åœ¨ <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> å’Œ <a href="https://github.com/zTrix/sata-license">SATA</a> åè®®ä¹‹æ¡æ¬¾ä¸‹æä¾›ï¼Œé™„åŠ æ¡æ¬¾äº¦å¯èƒ½åº”ç”¨'

extra_css:
  - stylesheets/extra.css
  - stylesheets/status.css
  - stylesheets/card.css

extra_javascript:
  - javascripts/mathjax.js # æ”¯æŒæ•°å­¦å…¬å¼ï¼Œref : https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/twemoji@latest/dist/twemoji.min.js

# Plugin
plugins:
  - search:
      separator: '[\s\u200b\-]'  # ä¸­æ–‡æœç´¢, pip install jieba
      # å‚è€ƒ:https://squidfunk.github.io/mkdocs-material/blog/2022/05/05/chinese-search-support/?h=%E4%B8%AD%E6%96%87
  - statistics
  #- git-revision-date #æ¯é¡µåº•éƒ¨æ˜¾ç¤ºæ–‡æ¡£æœ€åæ›´æ–°æ—¥æœŸï¼Œå®‰è£… pip install mkdocs-git-revision-date-plugin
  - git-revision-date-localized:  #æ¯ä¸ªé¡µé¢åº•éƒ¨æ·»åŠ æœ¬åœ°åŒ–æ›´æ–°å’Œåˆ›å»ºæ—¥æœŸï¼Œå®‰è£…pip install mkdocs-git-revision-date-localized-plugin
      type: date #æ—¥æœŸæ ¼å¼ï¼Œæœ‰æ•ˆå€¼ä¸ºdateã€datetimeã€iso_dateã€iso_datetime,timeago
      # fallback_to_build_date: true  #é»˜è®¤falseï¼Œå¯ç”¨åˆ™å›é€€åˆ°mkdocs buildæ‰§è¡Œçš„æ—¶é—´
      enable_creation_date: true  #æœ€åæ›´æ–°æ—¥æœŸæ—è¾¹æ˜¾ç¤ºä¸é¡µé¢å…³è”çš„æ–‡ä»¶çš„åˆ›å»ºæ—¥æœŸ
  - glightbox: # æ·»åŠ å›¾åƒç¼©æ”¾åŠŸèƒ½
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extensions:
# Python Markdown
  - toc: #ç›®å½•
      permalink: true # link for each title
      title: Table of Content 
    
  - admonition #è­¦å‘Šæˆ–æ ‡æ³¨
  - pymdownx.details #ç»†èŠ‚æŠ˜å 
  
  - attr_list #å±æ€§åˆ—è¡¨ï¼ˆæŒ‰é’®-é¢œè‰²å›¾æ ‡ï¼‰
  - md_in_html # å…è®¸æ·»åŠ HTMLå±æ€§å’ŒCSSç±»åˆ°MDä¸­
  - pymdownx.superfences: # å…è®¸ä»»æ„åµŒå¥—ä»£ç å’Œå†…å®¹å—
      custom_fences: # æ­¤é…ç½®å¯ç”¨å¯¹Mermaid.jså›¾è¡¨çš„æœ¬æœºæ”¯æŒ
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - abbr #ç¼©å†™æˆ–åè¯
  - def_list #å®šä¹‰åˆ—è¡¨
  - footnotes #è¡Œå†…è„šæ³¨
  - tables #è¡¨æ ¼
  - meta #å…ƒæ•°æ®
  - toc:
      toc_depth: 4

  - pymdownx.arithmatex: #æ•°å­¦å…¬å¼
      generic: true

  - pymdownx.betterem: #ç²—ä½“æ–œä½“
      smart_enable: all

  - pymdownx.critic 
  - pymdownx.caret #æ’å…¥è§’æ ‡ç¬¦å·(`^`)
  - pymdownx.keys #é”®ç›˜é”®å’Œç»„åˆ  
  - pymdownx.mark #åŒç­‰å·(`==`)
  - pymdownx.tilde # åˆ é™¤çº¿
  - pymdownx.details
  - pymdownx.smartsymbols #æ™ºèƒ½ç¬¦å·

  - pymdownx.emoji: # è¡¨æƒ…
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight #ä»£ç é«˜äº®ï¼Œå¯¹ä»£ç å—ï¼ˆSuperFencesï¼‰å’Œè¡Œå†…ä»£ç å—ï¼ˆInlineHiliteï¼‰çš„è¯­æ³•çªå‡ºæ˜¾ç¤º
  - pymdownx.inlinehilite #è¡Œå†…é«˜äº®
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.snippets: # å…è®¸å°†å…¶ä»–æ–‡ä»¶å†…å®¹æ’å…¥æ–‡ä»¶ï¼Œè¯­æ³•æ˜¯ --8<-- "filename.ext" ç­‰ï¼Œå‚è§ https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]

  - pymdownx.tabbed: #å†…å®¹é€‰é¡¹å¡
      alternate_style: true 
  - pymdownx.tasklist: #ä»»åŠ¡åˆ—è¡¨
      custom_checkbox: true
